/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carrentalsystem;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.logging.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alexa
 */
public class ad_manageCustPage extends javax.swing.JFrame {
    private String user;
    private String content, bookingID, name, IC, contact, email, carMod, start, end, total, status;
    private int selectRow, colCount, rowCount;
    private ArrayList<List> fileContentSplit = new ArrayList<>();
    private String [] statuses = {"--Select Status--","PENDING", "APPROVED", "PAID"};
    private String[] bookingDetail = new String[10];
    private String [] addtoRow = new String[10];
    private String[] columns = {"Booking ID", "Customer Name", "Customer IC/Passport", "Customer Contact No.", "Customer Email", "Car Model", "Start Date", "End Date", "Subtotal", "Status"};
    private DefaultTableModel model = new DefaultTableModel();
    private SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
    
    public ad_manageCustPage() {
        model.setColumnIdentifiers(columns);
        initComponents();
    }
    
    public ad_manageCustPage(String user) {
        this.user = user;
        model.setColumnIdentifiers(columns);
        initComponents();
    }
    
    public void setTextFields(String[] custBookingRow){
        this.bookingDetail = custBookingRow;
        bookingID = custBookingRow[0];
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        exitIcon = new javax.swing.JLabel();
        HomeIcon = new javax.swing.JLabel();
        BackIcon = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        custContact2 = new javax.swing.JTextField();
        custIC2 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        subtotal2 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        custBookingTbl2 = new javax.swing.JTable();
        deleteBtn2 = new javax.swing.JButton();
        updateBtn2 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        custName2 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        confirmBtn2 = new javax.swing.JButton();
        title2 = new javax.swing.JLabel();
        startDate2 = new com.toedter.calendar.JDateChooser();
        endDate2 = new com.toedter.calendar.JDateChooser();
        jLabel28 = new javax.swing.JLabel();
        custMail2 = new javax.swing.JTextField();
        Status2 = new javax.swing.JComboBox<>();
        carModel2 = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        exitIcon.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        exitIcon.setForeground(new java.awt.Color(255, 255, 255));
        exitIcon.setText("X");
        exitIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitIconMouseClicked(evt);
            }
        });

        HomeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/HomeIcon.png"))); // NOI18N
        HomeIcon.setText("jLabel8");
        HomeIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HomeIcon.setPreferredSize(new java.awt.Dimension(30, 30));
        HomeIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeIconMouseClicked(evt);
            }
        });

        BackIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BackIcon.png"))); // NOI18N
        BackIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackIconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(HomeIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 760, Short.MAX_VALUE)
                .addComponent(BackIcon)
                .addGap(18, 18, 18)
                .addComponent(exitIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomeIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exitIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(BackIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, -1));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0,150));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Customer IC/Passport:");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Customer Phone No.:");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Booked Car Model:");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Start Date:");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("End Date:");

        custContact2.setEditable(false);

        custIC2.setEditable(false);

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Subtotal:");

        subtotal2.setEditable(false);
        subtotal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtotal2subtotalActionPerformed(evt);
            }
        });

        custBookingTbl2.setModel(model);
        custBookingTbl2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                custBookingTbl2custBookingTblMouseReleased(evt);
            }
        });
        jScrollPane3.setViewportView(custBookingTbl2);

        deleteBtn2.setBackground(new java.awt.Color(51, 51, 51));
        deleteBtn2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        deleteBtn2.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn2.setText("Delete Booking");
        deleteBtn2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deleteBtn2.setBorderPainted(false);
        deleteBtn2.setOpaque(true);
        deleteBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtn2deleteBtnActionPerformed(evt);
            }
        });

        updateBtn2.setBackground(new java.awt.Color(51, 51, 51));
        updateBtn2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        updateBtn2.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn2.setText("Update Booking Details");
        updateBtn2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        updateBtn2.setBorderPainted(false);
        updateBtn2.setOpaque(true);
        updateBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtn2updateBtnActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Customer Name:");

        custName2.setEditable(false);

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Status:");

        confirmBtn2.setBackground(new java.awt.Color(120, 134, 107));
        confirmBtn2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        confirmBtn2.setText("SAVE");
        confirmBtn2.setBorderPainted(false);
        confirmBtn2.setOpaque(true);
        confirmBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBtn2confirmBtnActionPerformed(evt);
            }
        });

        title2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title2.setForeground(new java.awt.Color(255, 255, 255));
        title2.setText("Manage Customer Booking Page");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Customer Email:");

        custMail2.setEditable(false);

        Status2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Status2.setBorder(null);

        carModel2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        carModel2.setBorder(null);
        carModel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carModel2carModelActionPerformed(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel24)
                    .addComponent(jLabel27)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20)
                            .addComponent(jLabel28)
                            .addComponent(jLabel23)
                            .addComponent(jLabel22)
                            .addComponent(jLabel26))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(custName2, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                            .addComponent(endDate2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(subtotal2)
                            .addComponent(Status2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(92, 92, 92)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(updateBtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deleteBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(custIC2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(carModel2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(custMail2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(custContact2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
                        .addComponent(startDate2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator3)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(confirmBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(261, 261, 261)
                            .addComponent(title2))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 833, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(title2)
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(custName2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(custIC2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(custContact2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(custMail2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(carModel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(startDate2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(endDate2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(subtotal2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Status2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(deleteBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(updateBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(confirmBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 39, -1, 730));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ManageCust.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 890, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitIconMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitIconMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        FileHandling fh = new FileHandling("/Users/iankiew/NetBeansProjects/CarRentalSystem/src/TextFile/Car.txt");
        fh.readFile();
        this.fileContentSplit = fh.getfileContent();
        try {
            Status2.removeAllItems();
            for( int i = 0; i<4; i++){
                Status2.addItem(statuses[i]);
                if (Status2.getItemAt(i).contentEquals(this.bookingDetail[9])){
                    Status2.setSelectedIndex(i);
                }
            }
            carModel2.removeAllItems();
            carModel2.addItem("--Select Car Model--");
            for (int i = 1; i < fileContentSplit.size(); i++){
                content = fileContentSplit.get(i).get(0).toString();
                carModel2.addItem(content);
            } 
            for(int y = 0; y<carModel2.getItemCount(); y++){
                if(carModel2.getItemAt(y).equals(this.bookingDetail[5])){
                    carModel2.setSelectedIndex(y);
                }
            }
            custName2.setText(this.bookingDetail[1]);
            custIC2.setText(this.bookingDetail[2]);
            custContact2.setText(this.bookingDetail[3]);
            custMail2.setText(this.bookingDetail[4]);
            startDate2.setDate(df.parse(this.bookingDetail[6]));
            endDate2.setDate(df.parse(this.bookingDetail[7]));
            subtotal2.setText(this.bookingDetail[8]);
        } catch (ParseException ex) {
            Logger.getLogger(ad_manageCustPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        colCount = model.getColumnCount();
        FileHandling fh1 = new FileHandling("/Users/iankiew/NetBeansProjects/CarRentalSystem/src/TextFile/Booking.txt");
        fh1.readFile();
        this.fileContentSplit = fh1.getfileContent();
        for (int i = 1; i < fileContentSplit.size(); i++){
            for ( int y = 0; y < colCount; y++){
                content = fileContentSplit.get(i).get(y).toString();
                addtoRow[y] = content;
            }
            model.addRow(addtoRow);
        }
        
        if(bookingDetail != null){
            rowCount = custBookingTbl2.getRowCount();
            for(int i = 0; i< rowCount; i++){
                if(bookingDetail[0].equals(String.valueOf(model.getValueAt(i, 0)))){
                    selectRow = i;
                }
            }
            custBookingTbl2.setRowSelectionInterval(selectRow, selectRow);
        }
    }//GEN-LAST:event_formWindowOpened

    private void HomeIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeIconMouseClicked
        // TODO add your handling code here:
        CommonFunction cf = new CommonFunction();
        cf.DisplayDisposeForm(new ad_IndexPage(user), this);
    }//GEN-LAST:event_HomeIconMouseClicked

    private void BackIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackIconMouseClicked
        // TODO add your handling code here:
        CommonFunction cf = new CommonFunction();
        cf.DisplayDisposeForm(new ad_viewCustBookingPage(user), this);
    }//GEN-LAST:event_BackIconMouseClicked

    private void subtotal2subtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtotal2subtotalActionPerformed

    }//GEN-LAST:event_subtotal2subtotalActionPerformed

    private void custBookingTbl2custBookingTblMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_custBookingTbl2custBookingTblMouseReleased
        try {
            selectRow = custBookingTbl2.getSelectedRow();
            this.bookingID = String.valueOf(model.getValueAt(selectRow, 0));
            custName2.setText(String.valueOf(model.getValueAt(selectRow, 1)));
            custIC2.setText(String.valueOf(model.getValueAt(selectRow, 2)));
            custContact2.setText(String.valueOf(model.getValueAt(selectRow, 3)));
            custMail2.setText(String.valueOf(model.getValueAt(selectRow, 4)));
            carMod = String.valueOf(model.getValueAt(selectRow, 5));
            for(int y = 0; y<carModel2.getItemCount(); y++){
                if(carModel2.getItemAt(y).contentEquals(carMod)){
                carModel2.setSelectedIndex(y);
                }
            }
            startDate2.setDate(df.parse(String.valueOf(model.getValueAt(selectRow, 6))));
            endDate2.setDate(df.parse(String.valueOf(model.getValueAt(selectRow, 7))));
            subtotal2.setText(String.valueOf(model.getValueAt(selectRow, 8)));
            String stat = String.valueOf(model.getValueAt(selectRow, 9));
            for( int i = 0; i<Status2.getItemCount(); i++){
                if (Status2.getItemAt(i).contentEquals(stat)){
                    Status2.setSelectedIndex(i);
                }
            }
        } catch (ParseException ex) {
            Logger.getLogger(ad_manageCustPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_custBookingTbl2custBookingTblMouseReleased

    private void deleteBtn2deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtn2deleteBtnActionPerformed
        if (selectRow != -1){
            model.removeRow(selectRow);
            custName2.setText("");
            custIC2.setText("");
            custContact2.setText("");
            custMail2.setText("");
            carModel2.setSelectedIndex(0);
            startDate2.setDate(null);
            endDate2.setDate(null);
            subtotal2.setText("");
            Status2.setSelectedIndex(0);
        }
        else {
            JOptionPane.showMessageDialog(this, "Please Select a Row to Delete.", "Error Message", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_deleteBtn2deleteBtnActionPerformed

    private void updateBtn2updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtn2updateBtnActionPerformed
        // bookingID, name, IC, contact, email, carMod, start, end, total, status;
        boolean noStock = false;
        int selectedCarModel, selectedStatus;

        name = custName2.getText();
        IC = custIC2.getText();
        contact = custContact2.getText();
        email = custMail2.getText();
        carMod = carModel2.getSelectedItem().toString();
        start = df.format(startDate2.getDate());
        end = df.format(endDate2.getDate());
        status = Status2.getSelectedItem().toString();

        selectedCarModel = carModel2.getSelectedIndex();
        selectedStatus = Status2.getSelectedIndex();
        int[] selectedIndex = {selectedCarModel, selectedStatus};
        ValidateFields vcb = new ValidateFields();
        boolean validComboItem = vcb.ValidateComboBox(selectedIndex);

        CommonFunction cf = new CommonFunction();
        total = cf.calculateSubtotal(carMod, start, end);
        String [] values = {bookingID, name, IC, contact, email, carMod, start, end, total, status};
        Cus_AvailableCars aCars = new Cus_AvailableCars(startDate2.getDate(),endDate2.getDate());
        aCars.setBookingID(bookingID);
        if(validComboItem && aCars.DateValidation().equals("")){
            if(!aCars.carOutOfStock().isEmpty()){
                for (String cars: aCars.carOutOfStock()){
                    if(cars.equals(carMod)){
                        noStock = true;
                        JOptionPane.showMessageDialog(this, "Selected date is unavailable for "+carMod+". Please Choose another date.", "Error Message", JOptionPane.ERROR_MESSAGE);
                        break;
                    }
                    else {
                        noStock = false;
                    }
                }
            }
            if(!noStock){
                if(cf.checkEmpty(values) == false){
                    if(selectRow != -1){
                        model.removeRow(selectRow);
                        model.insertRow(selectRow, values);

                        custName2.setText("");
                        custIC2.setText("");
                        custContact2.setText("");
                        custMail2.setText("");
                        carModel2.setSelectedIndex(0);
                        startDate2.setDate(null);
                        endDate2.setDate(null);
                        subtotal2.setText("");
                        Status2.setSelectedIndex(0);
                    } else {
                        JOptionPane.showMessageDialog(this, "Please Select a Row to Update.", "Error Message", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        }else {
            if(validComboItem){
                JOptionPane.showMessageDialog(this, aCars.DateValidation(), "Error Message", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_updateBtn2updateBtnActionPerformed

    private void confirmBtn2confirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtn2confirmBtnActionPerformed
        ArrayList<List> fileData = new ArrayList<>();
        String[] columnHeaders = {"BOOKINGID", "CUS_NAME", "CUS_IC/PASSPORT", "CUS_CONTACTNO", "CUS_EMAIL", "CARMODEL", "STARTDATE", "ENDDATE", "SUBTOTAL", "STATUS"};
        fileData.add(Arrays.asList(columnHeaders));
        for(int row = 0; row<custBookingTbl2.getRowCount(); row++){
            String[] addToFile = new String[custBookingTbl2.getColumnCount()];
            for (int col = 0; col<custBookingTbl2.getColumnCount(); col++){
                String tableData = custBookingTbl2.getValueAt(row, col).toString();
                addToFile[col] = tableData;
            }
            fileData.add(Arrays.asList(addToFile));
        }
        FileHandling fh = new FileHandling("/Users/iankiew/NetBeansProjects/CarRentalSystem/src/TextFile/Booking.txt");
        fh.writeFile(fileData);
        JOptionPane.showMessageDialog(this, "Data Saved");
        CommonFunction cf = new CommonFunction();
        cf.DisplayDisposeForm(new ad_viewCustBookingPage(user), this);
    }//GEN-LAST:event_confirmBtn2confirmBtnActionPerformed

    private void carModel2carModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carModel2carModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carModel2carModelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ad_manageCustPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ad_manageCustPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ad_manageCustPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ad_manageCustPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ad_manageCustPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackIcon;
    private javax.swing.JLabel HomeIcon;
    private javax.swing.JComboBox<String> Status2;
    private javax.swing.JComboBox<String> carModel2;
    private javax.swing.JButton confirmBtn2;
    private javax.swing.JTable custBookingTbl2;
    private javax.swing.JTextField custContact2;
    private javax.swing.JTextField custIC2;
    private javax.swing.JTextField custMail2;
    private javax.swing.JTextField custName2;
    private javax.swing.JButton deleteBtn2;
    private com.toedter.calendar.JDateChooser endDate2;
    private javax.swing.JLabel exitIcon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator3;
    private com.toedter.calendar.JDateChooser startDate2;
    private javax.swing.JTextField subtotal2;
    private javax.swing.JLabel title2;
    private javax.swing.JButton updateBtn2;
    // End of variables declaration//GEN-END:variables
}
