/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carrentalsystem;

import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alexa
 */
public class ad_manageCarPage extends javax.swing.JFrame {
    private String user;
    private ArrayList<List> fileContentSplit = new ArrayList<>();
    private int selectRow, rowCount, colCount;
    private String[] carDetail = new String[5];
    private String [] addtoRow = new String[5];
    private String[] columns = {"Car Model", "Car Type", "No. of Seats", "Rental Price (Per Day)", "Quantity"};
    private String carName, carClass, noSeats, price, quan, content;
    private boolean sameTxt = false;
    private DefaultTableModel model = new DefaultTableModel();
    
    public ad_manageCarPage() {
        model.setColumnIdentifiers(columns);
        initComponents();
    }
    
    public ad_manageCarPage(String user) {
        this.user = user;
        model.setColumnIdentifiers(columns);
        initComponents();
    }
    
    public void setTextFields(String[] carRow){
        this.carDetail = carRow;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        carInfoTbl = new javax.swing.JTable();
        confirmBtn = new javax.swing.JButton();
        title1 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        exitIcon = new javax.swing.JLabel();
        HomeIcon = new javax.swing.JLabel();
        BackIcon = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rentPrice = new javax.swing.JTextField();
        numSeats = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        carType = new javax.swing.JTextField();
        carModel = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        remove = new javax.swing.JButton();
        editCar = new javax.swing.JButton();
        addCar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        carInfoTbl.setModel(model
        );
        carInfoTbl.setGridColor(new java.awt.Color(0, 0, 0));
        carInfoTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                carInfoTblMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(carInfoTbl);

        confirmBtn.setBackground(new java.awt.Color(120, 134, 107));
        confirmBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        confirmBtn.setText("SAVE");
        confirmBtn.setBorderPainted(false);
        confirmBtn.setOpaque(true);
        confirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBtnActionPerformed(evt);
            }
        });

        title1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title1.setForeground(new java.awt.Color(255, 255, 255));
        title1.setText("Info Page");

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(title1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
            .addComponent(jSeparator4)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(title1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(confirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jSeparator5))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 510, 480));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        exitIcon.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        exitIcon.setForeground(new java.awt.Color(255, 255, 255));
        exitIcon.setText("X");
        exitIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitIconMouseClicked(evt);
            }
        });

        HomeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/HomeIcon.png"))); // NOI18N
        HomeIcon.setText("jLabel8");
        HomeIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HomeIcon.setPreferredSize(new java.awt.Dimension(30, 30));
        HomeIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeIconMouseClicked(evt);
            }
        });

        BackIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BackIcon.png"))); // NOI18N
        BackIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackIconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(HomeIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 841, Short.MAX_VALUE)
                .addComponent(BackIcon)
                .addGap(18, 18, 18)
                .addComponent(exitIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomeIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(BackIcon)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(exitIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Quantity:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, 30));
        getContentPane().add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 275, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Rental Price (Per Day):");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, 30));
        getContentPane().add(rentPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 275, 30));
        getContentPane().add(numSeats, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 275, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("No. of Seats:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Car Type:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 30));

        carType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carTypeActionPerformed(evt);
            }
        });
        getContentPane().add(carType, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 275, 30));
        getContentPane().add(carModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 275, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Car Model:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 30));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0,120));

        title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Manage Car");

        remove.setBackground(new java.awt.Color(102, 102, 102));
        remove.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        remove.setForeground(new java.awt.Color(255, 255, 255));
        remove.setText("Remove Car");
        remove.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        remove.setBorderPainted(false);
        remove.setOpaque(true);
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });

        editCar.setBackground(new java.awt.Color(102, 102, 102));
        editCar.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        editCar.setForeground(new java.awt.Color(255, 255, 255));
        editCar.setText("Edit Car Info");
        editCar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        editCar.setBorderPainted(false);
        editCar.setOpaque(true);
        editCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCarActionPerformed(evt);
            }
        });

        addCar.setBackground(new java.awt.Color(102, 102, 102));
        addCar.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        addCar.setForeground(new java.awt.Color(255, 255, 255));
        addCar.setText("Add New Car");
        addCar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addCar.setBorderPainted(false);
        addCar.setOpaque(true);
        addCar.setPreferredSize(new java.awt.Dimension(118, 31));
        addCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(317, 317, 317)
                .addComponent(title)
                .addContainerGap(7, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(addCar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editCar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(remove, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 363, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editCar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(remove, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 470, 470));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ManageCar.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 470, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitIconMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitIconMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        carModel.setText(this.carDetail[0]);
        carType.setText(this.carDetail[1]);
        numSeats.setText(this.carDetail[2]);
        rentPrice.setText(this.carDetail[3]);
        quantity.setText(this.carDetail[4]);
        
        colCount = model.getColumnCount();
        FileHandling fh = new FileHandling("/Users/iankiew/NetBeansProjects/CarRentalSystem/src/TextFile/Car.txt");
        fh.readFile();
        fileContentSplit = fh.getfileContent();
        for (int y = 1; y < fileContentSplit.size(); y++){
            for (int i = 0; i<colCount; i++){
            content = fileContentSplit.get(y).get(i).toString();
            addtoRow[i] = content;
            }
             model.addRow(addtoRow);
        }
        
        if(carDetail[0] != null){
            rowCount = carInfoTbl.getRowCount();
            for(int i = 0; i< rowCount; i++){
                if(carDetail[0].equals(String.valueOf(model.getValueAt(i, 0)))){
                    selectRow = i;
                }
            }
            carInfoTbl.setRowSelectionInterval(selectRow, selectRow);
        }
    }//GEN-LAST:event_formWindowOpened

    private void HomeIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeIconMouseClicked
        // TODO add your handling code here:
        CommonFunction cf = new CommonFunction();
        cf.DisplayDisposeForm(new ad_IndexPage(user), this);
    }//GEN-LAST:event_HomeIconMouseClicked

    private void BackIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackIconMouseClicked
        // TODO add your handling code here:
        CommonFunction cf = new CommonFunction();
        cf.DisplayDisposeForm(new ad_viewCarInfoPage(user), this);
    }//GEN-LAST:event_BackIconMouseClicked

    private void carTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carTypeActionPerformed

    private void addCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCarActionPerformed
        //private String carName, carClass, noSeats, price, quan;
        carName = carModel.getText();
        carClass = carType.getText();
        noSeats = numSeats.getText();
        price = rentPrice.getText();
        quan = quantity.getText();

        String[] integerFields = {noSeats, price, quan};
        String [] values = {carName, carClass, noSeats, price, quan};
        ValidateFields vf = new ValidateFields();
        boolean validIntegers = vf.ValidateInteger(integerFields);
        CommonFunction cf = new CommonFunction();
        rowCount = carInfoTbl.getRowCount();
        for(int i = 0; i<rowCount; i++){
            if(carName.equals(String.valueOf(model.getValueAt(i, 0)))){
                sameTxt = true;
                break;
            }
            else {
                sameTxt = false;
            }
        }

        if(!cf.checkEmpty(values) && validIntegers){
            if (sameTxt){
                JOptionPane.showMessageDialog(this, "<html>Car Model <b>MUST</b> be <b>UNIQUE</b>.<html>", "Error Message", JOptionPane.ERROR_MESSAGE);
            }
            else{
                model.addRow(values);
                carModel.setText("");
                carType.setText("");
                numSeats.setText("");
                rentPrice.setText("");
                quantity.setText("");
            }
        }

    }//GEN-LAST:event_addCarActionPerformed

    private void editCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCarActionPerformed
        carName = carModel.getText();
        carClass = carType.getText();
        noSeats = numSeats.getText();
        price = rentPrice.getText();
        quan = quantity.getText();

        String[] integerFields = {noSeats, price, quan};
        String [] values = {carName, carClass, noSeats, price, quan};
        ValidateFields vf = new ValidateFields();
        boolean validIntegers = vf.ValidateInteger(integerFields);
        CommonFunction cf = new CommonFunction();
        if(validIntegers && cf.checkEmpty(values) == false){
            if (selectRow != -1){
                model.removeRow(selectRow);
                model.insertRow(selectRow, values);

                carModel.setText("");
                carType.setText("");
                numSeats.setText("");
                rentPrice.setText("");
                quantity.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Please Select a Row to Modify.", "Error Message", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_editCarActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        if (selectRow != -1){
            model.removeRow(selectRow);
            carModel.setText("");
            carType.setText("");
            numSeats.setText("");
            rentPrice.setText("");
            quantity.setText("");
        }
        else {
            JOptionPane.showMessageDialog(this, "Please Select a Row to Delete.", "Error Message", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_removeActionPerformed

    private void confirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtnActionPerformed
        ArrayList<List> fileData = new ArrayList<>();
        String[] columnHeaders = {"CARMODEL", "CARTYPE", "NUMOFSEATS", "RENTALPRICE(PERDAY)", "QUANTITY"};
        fileData.add(Arrays.asList(columnHeaders));
        for(int row = 0; row<carInfoTbl.getRowCount(); row++){
            String[] addToFile = new String[carInfoTbl.getColumnCount()];
            for (int col = 0; col<carInfoTbl.getColumnCount(); col++){
                String tableData = carInfoTbl.getValueAt(row, col).toString();
                addToFile[col] = tableData;
            }
            fileData.add(Arrays.asList(addToFile));
        }
        FileHandling fh = new FileHandling("/Users/iankiew/NetBeansProjects/CarRentalSystem/src/TextFile/Car.txt");
        fh.writeFile(fileData);
        JOptionPane.showMessageDialog(this, "Data Saved");
        CommonFunction cf = new CommonFunction();
        cf.DisplayDisposeForm(new ad_viewCarInfoPage(user), this);
    }//GEN-LAST:event_confirmBtnActionPerformed

    private void carInfoTblMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carInfoTblMouseReleased
        selectRow = carInfoTbl.getSelectedRow();
        carModel.setText(String.valueOf(model.getValueAt(selectRow, 0)));
        carType.setText(String.valueOf(model.getValueAt(selectRow, 1)));
        numSeats.setText(String.valueOf(model.getValueAt(selectRow, 2)));
        rentPrice.setText(String.valueOf(model.getValueAt(selectRow, 3)));
        quantity.setText(String.valueOf(model.getValueAt(selectRow, 4)));
    }//GEN-LAST:event_carInfoTblMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ad_manageCarPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ad_manageCarPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ad_manageCarPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ad_manageCarPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ad_manageCarPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackIcon;
    private javax.swing.JLabel HomeIcon;
    private javax.swing.JButton addCar;
    private javax.swing.JTable carInfoTbl;
    private javax.swing.JTextField carModel;
    private javax.swing.JTextField carType;
    private javax.swing.JButton confirmBtn;
    private javax.swing.JButton editCar;
    private javax.swing.JLabel exitIcon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField numSeats;
    private javax.swing.JTextField quantity;
    private javax.swing.JButton remove;
    private javax.swing.JTextField rentPrice;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title1;
    // End of variables declaration//GEN-END:variables
}
