package carrentalsystem;

import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author alexa
 */
public class ad_viewCarInfoPage extends javax.swing.JFrame {
    private String user;
    private ArrayList<List> fileContentSplit = new ArrayList<>();
    private int row, colCount;
    private String content, search;
    private String[] selectedRow = new String[5];
    private String [] addtoRow = new String[5];
    private String[] columns = {"Car Model", "Car Type", "No. of Seats", "Rental Price (Per Day)", "Quantity"};
    private DefaultTableModel model = new DefaultTableModel();

    /**
     * Creates new form ad_manageCarPage
     */
    public ad_viewCarInfoPage() {
        model.setColumnIdentifiers(columns);
        initComponents();
    }
    
    public ad_viewCarInfoPage(String user) {
        this.user = user;
        model.setColumnIdentifiers(columns);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        carInfoTbl = new javax.swing.JTable();
        searchIcon = new javax.swing.JLabel();
        searchbar = new javax.swing.JTextField();
        addNewCarBtn = new javax.swing.JButton();
        updateCarInfoBtn = new javax.swing.JButton();
        delCarInfoBtn = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        exitIcon = new javax.swing.JLabel();
        HomeIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(120, 134, 107));

        carInfoTbl.setModel(model

        );
        carInfoTbl.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(carInfoTbl);

        searchIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SearchIcon.png"))); // NOI18N
        searchIcon.setText("icon");
        searchIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchIconMouseClicked(evt);
            }
        });

        searchbar.setForeground(new java.awt.Color(204, 204, 204));
        searchbar.setText("search...");
        searchbar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        searchbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                searchbarMouseReleased(evt);
            }
        });
        searchbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbarActionPerformed(evt);
            }
        });

        addNewCarBtn.setBackground(new java.awt.Color(0, 0, 0));
        addNewCarBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        addNewCarBtn.setForeground(new java.awt.Color(255, 255, 255));
        addNewCarBtn.setText("Add New Car");
        addNewCarBtn.setBorderPainted(false);
        addNewCarBtn.setOpaque(true);
        addNewCarBtn.setPreferredSize(new java.awt.Dimension(113, 31));
        addNewCarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewCarBtnActionPerformed(evt);
            }
        });

        updateCarInfoBtn.setBackground(new java.awt.Color(0, 0, 0));
        updateCarInfoBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        updateCarInfoBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateCarInfoBtn.setText("Update Car Info");
        updateCarInfoBtn.setBorderPainted(false);
        updateCarInfoBtn.setOpaque(true);
        updateCarInfoBtn.setPreferredSize(new java.awt.Dimension(129, 31));
        updateCarInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCarInfoBtnActionPerformed(evt);
            }
        });

        delCarInfoBtn.setBackground(new java.awt.Color(0, 0, 0));
        delCarInfoBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        delCarInfoBtn.setForeground(new java.awt.Color(255, 255, 255));
        delCarInfoBtn.setText("Delete Car Info");
        delCarInfoBtn.setBorderPainted(false);
        delCarInfoBtn.setOpaque(true);
        delCarInfoBtn.setPreferredSize(new java.awt.Dimension(116, 31));
        delCarInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delCarInfoBtnActionPerformed(evt);
            }
        });

        title.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        title.setText("Car Info Page");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(searchbar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(searchIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addNewCarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(updateCarInfoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(delCarInfoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(title)
                        .addGap(267, 267, 267))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(title)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(delCarInfoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(updateCarInfoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addNewCarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(searchIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchbar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 810, 560));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        exitIcon.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        exitIcon.setForeground(new java.awt.Color(255, 255, 255));
        exitIcon.setText("X");
        exitIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitIconMouseClicked(evt);
            }
        });

        HomeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/HomeIcon.png"))); // NOI18N
        HomeIcon.setText("jLabel8");
        HomeIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HomeIcon.setPreferredSize(new java.awt.Dimension(30, 30));
        HomeIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeIconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(HomeIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 725, Short.MAX_VALUE)
                .addComponent(exitIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(HomeIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitIconMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitIconMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        FileHandling fh = new FileHandling("/Users/iankiew/NetBeansProjects/CarRentalSystem/src/TextFile/Car.txt");
        fh.readFile();
        colCount = model.getColumnCount();
        fileContentSplit = fh.getfileContent();
        
        for (int y = 1; y < fileContentSplit.size(); y++){
            for (int i = 0; i<colCount; i++){
                content = fileContentSplit.get(y).get(i).toString();
                addtoRow[i] = content;
            }
             model.addRow(addtoRow);
        }

    }//GEN-LAST:event_formWindowOpened

    private void addNewCarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewCarBtnActionPerformed
        CommonFunction cf = new CommonFunction();
        cf.DisplayDisposeForm(new ad_manageCarPage(user), this);
    }//GEN-LAST:event_addNewCarBtnActionPerformed

    private void updateCarInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCarInfoBtnActionPerformed
        row = carInfoTbl.getSelectedRow();
        if (row == -1){
            JOptionPane.showMessageDialog(this, "Please select a row.", "Error Message", JOptionPane.ERROR_MESSAGE);
        } else {
            for (int i = 0; i < colCount; i++){
                selectedRow[i] = String.valueOf(model.getValueAt(row, i));
            }
            ad_manageCarPage manageCar = new ad_manageCarPage(user);
            manageCar.setTextFields(selectedRow);
            CommonFunction cf = new CommonFunction();
            cf.DisplayDisposeForm(manageCar, this);
        }
    }//GEN-LAST:event_updateCarInfoBtnActionPerformed

    private void delCarInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delCarInfoBtnActionPerformed
        row = carInfoTbl.getSelectedRow();
        if (row == -1){
            JOptionPane.showMessageDialog(this, "Please select a row.", "Error Message", JOptionPane.ERROR_MESSAGE);
        } else {
            for (int i = 0; i < colCount; i++){
                selectedRow[i] = String.valueOf(model.getValueAt(row, i));
            }
            ad_manageCarPage manageCar = new ad_manageCarPage(user);
            manageCar.setTextFields(selectedRow);
            CommonFunction cf = new CommonFunction();
            cf.DisplayDisposeForm(manageCar, this);
        }
    }//GEN-LAST:event_delCarInfoBtnActionPerformed

    private void searchbarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchbarMouseReleased
        searchbar.setText("");
    }//GEN-LAST:event_searchbarMouseReleased

    private void searchbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchbarActionPerformed

    private void HomeIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeIconMouseClicked
        // TODO add your handling code here:
        CommonFunction cf = new CommonFunction();
        cf.DisplayDisposeForm(new ad_IndexPage(user), this);
    }//GEN-LAST:event_HomeIconMouseClicked

    private void searchIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchIconMouseClicked
        // TODO add your handling code here:
        boolean searchFound = true;
        search = searchbar.getText();
        
        for (int y = 1; y < fileContentSplit.size(); y++){
            if(search.equals(fileContentSplit.get(y).get(0))){
                for (int i = 0; i<colCount; i++){
                    content = fileContentSplit.get(y).get(i).toString();
                    addtoRow[i] = content;
                }
                model.setRowCount(0);
                model.addRow(addtoRow);
                searchFound = true;
                break;
            }
            else{
                searchFound = false;
            }
        }
        
        if(!searchFound){
            JOptionPane.showMessageDialog(this, "Car Model does not exist. Please enter a valid Car Model.", "Error Message", JOptionPane.ERROR_MESSAGE);
            model.setRowCount(0);
            for (int i = 1; i < fileContentSplit.size(); i++){
                for ( int y = 0; y < colCount; y++){
                    content = fileContentSplit.get(i).get(y).toString();
                    addtoRow[y] = content;
                }
                model.addRow(addtoRow);
            }
        }
    }//GEN-LAST:event_searchIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ad_viewCarInfoPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ad_viewCarInfoPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ad_viewCarInfoPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ad_viewCarInfoPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ad_viewCarInfoPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HomeIcon;
    private javax.swing.JButton addNewCarBtn;
    private javax.swing.JTable carInfoTbl;
    private javax.swing.JButton delCarInfoBtn;
    private javax.swing.JLabel exitIcon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel searchIcon;
    private javax.swing.JTextField searchbar;
    private javax.swing.JLabel title;
    private javax.swing.JButton updateCarInfoBtn;
    // End of variables declaration//GEN-END:variables
}
